<?php 
use Rudra\Container\Facades\Rudra;
use App\Containers\Blog\UI\UI;
?>

<br>

<div class="row row-cols-1 row-cols-md-3 g-4" data-masonry='{"percentPosition": true }'>

<?php foreach($materials as $material): ?>

    <div class="col">
    <div class="card">
    <a href="<?= Rudra::config()->get('url') ?>/material/<?= $material['id'] ?>_<?= $material['slug'] ?>">
    <?php if (!empty($material['image'])): ?><img src="<?= Rudra::config()->get('url') ?>/images/<?= $material['image'] ?>" class="card-img-top" alt="<?= $material['title']?>"><?php endif; ?>
    </a>
      <div class="card-body">
        <h5 class="card-title"><a class="link-secondary link-underline link-underline-opacity-0" href="<?= Rudra::config()->get('url') ?>/material/<?= $material['id'] ?>_<?= $material['slug'] ?>"><?= $material['title']?></a></h5>
        <!-- <p class="card-text"><?= htmlspecialchars_decode($material['text'])?></p> -->
      </div>
    </div>
  </div>

<?php endforeach; ?>

</div>

<?php if (count($links) > 1): ?>
    <?= UI::renderLinks($links, $page, $pg_limit, '/page/'); ?>
<?php endif; ?>