<?php use Rudra\Container\Facades\Rudra; ?>

<form action="<?= Rudra::config()->get('url') ?>/admin/material/create" method="post">
  <div class="mb-3">
    <label for="title" class="form-label">Заголовок</label>
    <input type="text" class="form-control" id="title" name="title" value="">
  </div>
  <div class="mb-3">
    <label for="text" class="form-label">Текст</label>
    <textarea class="form-control" id="text" name="text"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Добавить</button>
</form>