<?php 
use Rudra\Container\Facades\Rudra; 
use Rudra\Container\Facades\Session;
?>

<br>
<form action="<?= Rudra::config()->get('url') ?>/admin/material/create" method="post" enctype="multipart/form-data">
<input type='hidden' name='csrf_field' value='<?= Session::get('csrf_token')[0]; ?>'>
<input type='hidden' name='redirect'>
<div class="mb-3">
    <label for="file" class="form-label">Фото</label>
    <input type="file" name="file" id="file">
  </div>
  <div class="mb-3">
    <label for="title" class="form-label">Заголовок</label>
    <input type="text" class="form-control" id="title" name="title" value="">
  </div>
  <div class="mb-3">
    <label for="text" class="form-label">Текст</label>
    <textarea class="form-control" id="text" name="text"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Добавить</button>
</form>